- name: make direcotry for clouds.yaml
  file:
    path: ~/.config/openstack
    state: directory

- name: copy over clouds.yaml file
  copy:
    src: ~/.config/openstack/clouds.yaml
    dest: ~/.config/openstack
    mode: '0755'

