- name: Get flavor list
  hosts: localhost
  tasks:
        - name: Query openstack
          openstack.cloud.compute_flavor_info:
          register: flavor_list


        - name: Generate list
          set_fact:
                  my_list: "{{ my_list | default([]) + [item.name | string] }}"
          with_items:
                  - "{{ flavor_list.openstack_flavors }}"
        - name: Remove GPU flavors
          set_fact:
                  my_list: "{{ my_list | reject('search', flavor_list_search) | list }}"
          vars:
                  flavor_list_search: 'g-'

        - name: print final list
          debug:
                  msg: "{{ my_list }}"
