- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 300
- name: get OS
  setup:
    gather_subset:
      - distribution
  when: ansible_distribution is not defined

- name: Update packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  become: true
  when: ansible_distribution == 'Ubuntu'
  register: result
  until: result is not failed
  retries: 5
  delay: 30

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
  become: true

