- name: Install openstack
  apt:
    name: python3-openstackclient
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install openstack Rocky
  dnf:
    name: python3-openstackclient
    state: present
  become: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed
  when: ansible_distribution == 'Rocky'

- name: make direcotry for clouds.yaml
  file:
    path: ~/.config/openstack
    state: directory

- name: copy over clouds.yaml file
  copy:
    src: ~/.config/openstack/clouds.yaml
    dest: ~/.config/openstack
    mode: '0755'
