---
- name: Automatically create and destroy VMs
  hosts: localhost
  vars:
    images: ["ubuntu-focal-20.04-nogui", "rocky-8-nogui"]

  pre_tasks:
    - name: Install openstack
      ansible.builtin.package:
        name: python3-openstacksdk
        state: present
      become: true

    - name: Query openstack
      openstack.cloud.compute_flavor_info:
        ram: "<200000"
      register: flavor_list

    - name: Generate list
      ansible.builitin.set_fact:
        flavors: "{{ flavors | default([]) + [item.name | string] }}"
      with_items:
        - "{{ flavor_list.openstack_flavors }}"

    - name: Remove GPU flavors
      ansibel.builtin.set_fact:
        flavors: "{{ flavors | reject('search', flavor_list_search) | list }}"
      vars:
        flavor_list_search: 'g-'
  
    - name: Print flavors
      debug: var=flavors
  
    - name: Print images
      debug: var=images

  tasks:
    - name: Storage Benchmark
      include_role: 
        name: storage_benchmark
      with_nested:
        - "{{ flavors }}"
        - "{{ images }}"

    - name: Create hepscore machines
      include_tasks: common/create_vm.yaml
      vars:
        group: hepscore
      with_nested:
        - "{{ flavors }}"
        - "{{ images }}"
  
    - name: Run HEPScore
      include_role: 
          name: hepscore

    - name: Destroy hepscore machines
      include_tasks: common/destroy_vm.yaml
      with_nested:
        - "{{ flavors }}"
        - "{{ images }}"
