- hosts: storage
  name: Update Machine
  gather_facts: false   # We may still be booting
  pre_tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        timeout: 300
    - name: Gather facts
      setup:
  roles:
    - update_machine

- hosts: storage
  name: Run storage roles
  vars_files:
     - ./vars/storage.yaml
  
  roles:
    - role: setup_openstack
    - role: update_machine
    - role: setup_storage_benchmark
    - role: attach_volume
    - role: run_storage_benchmark


- hosts: compute
  name: Run Compute roles
  vars_files:
     - ./vars/hepscore.yaml
  roles:
    - role: update_machine
    - role: hepscore
