- hosts: storage
  name: Update Machine
  gather_facts: false   # We may still be booting
  pre_tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        timeout: 300
    - name: Gather facts
      setup:
  roles:
    - update_machine

- hosts: storage
  name: Run storage playbook
  vars_files:
     - ./vars/storage.yaml
  roles:
    - role: update_machine
    - role: move_clouds_yaml
    - role: setup_storage_benchmark
    - role: run_storage_benchmark
    - role: attach_volume

- hosts: compute
  name: Run CPU playbook
  vars_files:
     - ./vars/compute.yaml
  roles:
    - role: update_machine
    - role: move_clouds_yaml
    - role: hepscore
