plugin: openstack.cloud.openstack

all_projects: false
expand_hostvars: false
fail_on_errors: true
only_clouds:
  - "openstack"
strict: true
private: true

groups: 
  <group_name>: |
     'group' in openstack.metadata and '<group_name>' in openstack.metadata['group']
