plugin: openstack.cloud.openstack

all_projects: false
expand_hostvars: false
fail_on_errors: true
only_clouds:
  - "openstack"
strict: true
private: true

groups: 
  storage: |
     'group' in openstack.metadata and 'storage' in openstack.metadata['group']
  # cpu: |
  #    'group' in openstack.metadata and 'cpu' in openstack.metadata['group']
