ansible_host: 10.5.0.32
bootstrapped: false
configured_bridge: true
configured_interfaces: true
configured_router: true
configured_service: true
configured_system: true
hostname: lfsw14
reinstall: false
system_location: r26rack887
update: false
vlan_interfaces:
-   id: '450'
    network: 172.16.208.192/27
