ansible_host: 10.5.0.32
bgp_router_id: 3.3.2.14
bootstrapped: true
eth0_ip: "{{ansible_host}}/16"
fqdn: lfsw14.r26.cloud.internal
hostname: lfsw14
lo_ip: 10.10.20.14/32
reinstall: false
system_location: r26rack887
update: false
vlan_interfaces:
-   id: '450'
    network: 172.16.208.192/27
