---
- name: Deploy and run hepscore
  hosts: hepscore
  tasks:
   - name: Template metrics sending script
     ansible.builtin.template:
      src: /home/adamg/cloud/benchmarking/hepscore-ansible/files/send_to_victoria.sh
      dest: /home/rhw13944/send_to_victoria.sh
      mode: a+x

   - name: Install apptainer
     become: true
     ansible.builtin.dnf:
      name: apptainer
      state: latest

   - name: Login to harbor
     ansible.builtin.command:
      apptainer remote login -u {{ harbor_username }} -p {{ harbor_password }} oras://harbor.stfc.ac.uk

   - name: Pull apptainer file
     ansible.builtin.command: apptainer pull oras://harbor.stfc.ac.uk/stfc-cloud-staging/hepscore:latest

   - name: Run apptainer file
     ansible.builtin.command: apptainer run /home/rhw13944/hepscore.sif

   - name: Send score to VictoriaMetrics
     ansible.builtin.command: ./send_to_victoria.sh
