---
- name: push inventory to nodes
  hosts: switches
  gather_facts: false
  vars:
    ansible_password: "{{ vault_default_password }}"
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - push_nvue_facts

- name: Fetch config from nodes
  hosts: switches
  gather_facts: false
  vars:
    ansible_password: "{{ vault_default_password }}"
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - gather_nvue_facts
