---
- name: Configure border switches for STFC Cloud
  hosts: switches
  connection: paramiko
  gather_facts: false
  vars:
    ansible_password: "{{ vault_default_password }}"
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - update
