- name: Mount ephemeral SMB volume
  ansible.posix.mount:
    src: "{{ share_path }}"
    path: /mnt/manila{{ vm_count }}
    opts: "name={{ user }},secret={{ access_key }}"
    fstype: ceph
    state: ephemeral
  become: true

- name: Change manila folder owner
  shell: chown diz41711 /mnt/manila{{ vm_count }}
  become: true