- name: set flavor
  set_fact:
    vm_flavor: "{{ item.0 }}"

- name: set image
  set_fact:
    vm_image: "{{ item.1 }}"

- name: Print creation info
  debug:
    msg:
      - "Creating:"
      - "Flavor: {{ vm_flavor }}"
      - "Image: {{ vm_image }}"

- name: create VM
  os_server:
      flavor: "{{ vm_flavor }}"
      image: "{{ vm_image }}"
      name: "Meerkat-{{ vm_flavor }}-{{ vm_image }}"
      key_name: "{{ key_name }}"
      state: present
      network: Internal
      auto_ip: no
      timeout: 200
  register: vm_info

- name: Get IP address of VM
  set_fact:
    vm_IP: "{{ vm_info.server.addresses.Internal[0].addr }}"

- name: Print VM IP
  debug:
    msg: "{{ vm_IP }}"

- name: Add VM to hosts
  add_host:
    hostname: "rhw13944@{{ vm_IP }}"
    groups: "{{ benchmark }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_image: "{{ vm_image }}"
