- name: Print creation info
  debug:
    msg:
      - "Creating:"
      - "Flavor: {{ vm_flavor }}"
      - "Image: {{ vm_image }}"

- name: create VM
  os_server:
      flavor: "{{ vm_flavor }}"
      image: "{{ vm_image }}"
      name: "{{ vm_name }}"
      key_name: "{{ key_name }}"
      state: present
      network: Internal
      auto_ip: no
      timeout: 200
  register: vm_info

- name: Get IP address of VM
  set_fact:
    vm_IP: "{{ vm_info.openstack.addresses.Internal[0].addr }}"

- name: Print VM IP
  debug:
    msg: "{{ vm_IP }}"
