- name: Print deletion info
  debug:
    msg:
      - "Deleting:"
      - "Flavor: {{ vm_flavor }}"
      - "Image: {{ vm_image }}"

- name: Delete VM
  openstack.cloud.server:
      name: "Meerkat-{{ vm_flavor }}-{{ vm_image }}"
      state: absent